name: Linux Build (Vulkan)

on:
  push:
    branches: [ "vulkan" ]
  pull_request:
    branches: [ "vulkan" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ninja-build \
          autoconf automake libtool autoconf-archive m4 pkg-config \
          build-essential \
          libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev \
          libgl1-mesa-dev \
          python3 python3-dev python3-venv \
          libssl-dev libffi-dev

    - name: Cache vcpkg installed
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/vcpkg
          vcpkg_installed
        key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
        
    - name: Cache builds directory
      uses: actions/cache@v4
      with:
        path: builds
        key: build-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
        restore-keys: |
          build-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}-
          build-${{ runner.os }}-

    - uses: lukka/get-cmake@latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: "./vcpkg.json"

    - name: Run CMake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: "ninja-multi-vcpkg"
        buildPreset: "release"

    - name: Create zip archive
      run: |
        releaseRel="builds/ninja-multi-vcpkg/Release"
        zipFullPath="$releaseRel/ion-latest-linux.zip"
        paths=()

        ionExeRel="$releaseRel/ion-development"
        if [[ -f "$ionExeRel" ]]; then
          paths+=("$ionExeRel")
        fi

        libraries=$(find "$releaseRel" -type f -name "*.so")
        if [[ ! -z "$libraries" ]]; then
          for file in $libraries; do
            paths+=("$file")
          done
        fi

        if [[ -d "assets" ]]; then
          paths+=("assets")
        fi

        [[ ${#paths[@]} -gt 0 ]]
        zip -r "$zipFullPath" "${paths[@]}"

    - name: Release built file
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GH_TOKEN }}"
        automatic_release_tag: "latest-linux-vulkan"
        prerelease: true
        title: "Pre-release Build (Linux, Vulkan)"
        files: |
          builds/ninja-multi-vcpkg/Release/ion-latest-linux-vulkan.zip
